config/routes.rb
Rails.application.routes.draw do
  resources :users
  namespace :admin do
    resources :gifs
    resources :categories
  end

  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :categories, only: [:index, :show]
  resources :favorites
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :gifs
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :gif
  belongs_to :user
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  belongs_to :category
  has_many :favorites
  has_many :users, through: :favorites

  def self.generate_gif(search_term)
    search = search_term.gsub(' ', '+')
    uri = URI("http://api.giphy.com/v1/gifs/search?q=#{search}&limit=100&api_key=dc6zaTOxFJmzC")
    response = Net::HTTP.get uri
    giphy = JSON.parse response
    gif = giphy['data'].sample
    { uid: gif['id'], url: gif['images']['original']['url'] }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :favorites
  has_many :gifs, through: :favorites
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  enum role: ['defualt', 'admin']
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show]

  def index
    @categories = Category.all
  end

  def show
    @gifs = @category.gifs
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/admin/gifs_controller.rb
class Admin::GifsController < Admin::BaseController
  def index
    @gifs = Gif.all
  end

  def new
  end

  def create
    gif_params = Gif.generate_gif(params[:search_term][:category])
    @category = Category.find_or_create_by(name: params[:search_term][:category])
    @gif = @category.gifs.new(gif_params)
    if @gif.save
      flash[:notice] = "Successfully created Gif"
      redirect_to admin_gif_path(@gif)
    else
      flash.now[:error] = @gif.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @gif = Gif.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :current_admin?

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_user

  def index
    @favorites = @user.gifs
  end

  def create
    gif = Gif.find_by(uid: params[:uid])
    Favorite.create(user_id: @user.id, gif_id: gif.id)
    flash[:notice] = "Gif added to favorites"
    redirect_to favorites_path
  end

  def destroy
    @favorite = Favorite.find_by(user_id: session[:user_id], gif_id: params[:id])
    @favorite.destroy
    flash.now[:notice] = "Successfully removed favorite"
    render :index
  end

  private

  def set_user
    @user = User.find(session[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:error] = "Invalid Login. Try Again."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Goodbye!"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:error] = "You fucked up"
      render :new
    end
  end

  def show

  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h3> Categories </h3>

<ul>
  <% @categories.each do |cat| %>
  <li><%= link_to cat.name, admin_category_path(cat) %></li>
  <% end %>
</ul>

app/views/admin/categories/show.html.erb
<h2> Gifs for '<%= @category.name %>' </h2>

<ul>
  <% @gifs.each do |gif| %>
  <li id="<%= gif.uid %>"><img src="<%= gif.url %>" /> </li>
  <% end %>
</ul>

app/views/admin/gifs/new.html.erb
<div class="row">
  <div class="col s6 offset-s3 pushdown">
    <%= form_for :search_term, url: admin_gifs_path do |f| %>
      <%= f.label :category, 'Gif Search Term' %>
      <%= f.text_field :category %>
      <%= f.submit 'Create Gif', class: 'btn red' %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<h3> Categories </h3>

<div class="row">
  <% @categories.each do |cat| %>
  <div class="col s4 gifs">
    <%= link_to cat.name, category_path(cat) %><br>
    <%= link_to image_tag(cat.gifs.first.url), category_path(cat) %>
  </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<h2> Gifs for '<%= @category.name %>' </h2>

<div class="row">
  <% @category.gifs.each do |gif| %>

    <div id="<%= gif.uid %>" class='col s4 gifs'>
      <%= link_to 'Add to favorites', favorites_path(uid: gif.uid), method: :post %><br>
      <img src="<%= gif.url %>" />
    </div>
  <% end %>
</div>

app/views/favorites/index.html.erb
<p>
  <%= flash[:notice] %>
</p>
<div class="row">
  <% @favorites.each do |f| %>
  <div class='col s4 gifs'>
    <img src="<%= f.url %>" /><br>
    <%= link_to "Delete from favorites", favorite_path(f), method: :delete %>
  </div>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='yellow lighten-4'>
  <div class="row blue">
    <div class="container">

      <div class="col s6">
        <%= image_tag "giphyfavlogo.png", class: 'pad' %>
      </div>
      <div class="col s6 center">
        <ul class="pushdown">
          <li><%= link_to 'Favorites', favorites_path, class: 'yellow-text menunav' %></li>
          <li><%= link_to 'Categories', categories_path, class: 'yellow-text menunav' %></li>
        <% if current_user %>
          <li> <%= link_to 'Logout', logout_path, method: :delete, class: 'yellow-text menunav' %></li>
        <% else %>
          <li> <%= link_to 'Login', login_path, class: 'yellow-text menunav' %></li>
        <% end %>
        <% if current_admin? %>
          <li> <%= link_to 'Add New Gif', new_admin_gif_path, class: 'yellow-text menunav' %></li>
        <% end %>
        <ul>
      </div>
    </div>

  </div>

<div class="container">

  <%= yield %>

</div>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<p> Hello, <%= @user.username.capitalize %>